name: BTClock CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build BTClock firmware
        run: pio run -e esp32wemos-s3-mini_BW 

      - name: Build BTClock filesystem
        run: pio run -e esp32wemos-s3-mini_BW --target buildfs

      - name: Install esptools.py
        run: pip install --upgrade esptool

      - name: Create merged firmware binary
        run: mkdir -p output && esptool.py --chip esp32s3 merge_bin -o output/full-firmware.bin --flash_mode dio 0x0000 .pio/build/esp32wemos-s3-mini_BW/bootloader.bin 0x8000 .pio/build/esp32wemos-s3-mini_BW/partitions.bin 0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 .pio/build/esp32wemos-s3-mini_BW/firmware.bin 0x330000 .pio/build/esp32wemos-s3-mini_BW/spiffs.bin

      - name: Create checksum for merged binary
        run: shasum -a 256 output/full-firmware.bin | awk '{print $1}' > output/full-firmware.sha256

      - name: Write commit hash to file
        run: echo $GITHUB_SHA > output/commit.txt

      - name: Write build date to file
        run: echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > output/date.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            .pio/build/esp32wemos-s3-mini_BW/*.bin
            output/full-firmware.bin
            output/full-firmware.sha256

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: main
          commit: main
          artifacts: "output/full-firmware.bin,output/full-firmware.sha256,.pio/build/esp32wemos-s3-mini_BW/*.bin"
          allowUpdates: true
          removeArtifacts: true
      - name: Pushes full-firmware.bin to web flasher
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          target-directory: firmware/
          destination-github-username: 'btclock'
          destination-repository-name: 'web-flasher'
          target-branch: btclock
          user-name: ${{github.actor}}
          user-email: ${{github.actor}}@users.noreply.github.com